apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-map
  namespace: default
data:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "movieApp"
  POSTGRES_AUTH_TABLE: "users"
  POSTGRES_DATA_TABLE: "movies"
  TMDB_API_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlYWFiZmY2ZDlhOGZhMjcxZGQ1NzMyYjBjOTRhNmQ5NyIsIm5iZiI6MTc2ODkxNzI2Ni4zMzksInN1YiI6IjY5NmY4OTEyMmFhZGUzNDJmOGZlMTEyMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.d0XWEipxQh2O8hPrMD1Y0re6ao2k6uuCvTW225RwEkk"