apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
    - image: lucaslazaroiu/ccproject:api-service
      name: api-service-container
      env:
        - name: PGUSER
          value: "admin"
        - name: PGPASSWORD
          value: "admin"
        - name: PGAUTHTABLE
          value: "users"
        - name: PGDATATABLE
          value: "postgres"
        - name: PGHOST
          value: "postgres"
        - name: PGPORT
          value: "5432"
