apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
