apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
  labels:
    app: auth
spec:
  replicas: 1  # Number of replicas you want for your auth container
  selector:
    matchLabels:
      app: auth  # Match the label of the pod to ensure the deployment controls the pods
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-service-container
          image: lucaslazaroiu/ccproject:auth-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: PGUSER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: PGDATABASE
              value: "movieApp"
            - name: PGAUTHTABLE
              value: "users"
            - name: PGHOST
              value: "postgres"
            - name: PGHOSTADDR
              value: "10.96.92.3" # PGHOSTADDR
            - name: PGPORT
              value: "5432"
            - name: CATALOGUE_SERVICE_URL
              value: "http://10.96.80.98:8091" # CATALOGUE_SERVICE_URL
            - name: RECOMMENDATION_SERVICE_URL
              value: "http://10.96.247.13:8092" # RECOMMENDATION_SERVICE_URL
            - name: REVIEW_SERVICE_URL
              value: "http://10.96.25.87:8093" # REVIEW_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              value: "http://10.96.220.69:8094" # NOTIFICATION_SERVICE_URL