apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 5000
  selector:
    app: auth
