apiVersion: v1
kind: Pod
metadata:
  name: catalogue-pod
  labels:
    app: catalogue
spec:
  containers:
    - image: lucaslazaroiu/ccproject:catalogue-service
      name: catalogue-service-container
      ports:
        - containerPort: 8091
      env:
        - name: PGUSER
          value: "admin"
        - name: PGPASSWORD
          value: "admin"
        - name: PGDATABASE
          value: "movieApp"
        - name: PGDATATABLE
          value: "movies"
        - name: PGHOST
          value: "postgres"
        - name: PGPORT
          value: "5432"
