apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 5001
  selector:
    app: catalogue
