apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer-clusterrole
rules:
- apiGroups: ["*"] # All API groups
  resources: ["*"] # All resources
  verbs: ["*"]     # All verbs (get, list, watch, create, update, delete, etc.)