apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
  namespace: default
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation-service-container
          image: lucaslazaroiu/ccproject:recommendation-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          env:
            - name: PGUSER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: PGDATABASE
              value: "movieApp"
            - name: PGHOST
              value: "postgres"
            - name: PGHOSTADDR
              value: "10.96.120.128" # PGHOSTADDR
            - name: PGPORT
              value: "5432"
