apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  namespace: default
  labels:
    app: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review-service-container
          image: lucaslazaroiu/ccproject:review-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
          env:
            - name: PGUSER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: PGDATABASE
              value: "movieApp"
            - name: PGHOST
              value: "postgres"
            - name: PGHOSTADDR
              value: "10.96.92.3" # PGHOSTADDR
            - name: PGPORT
              value: "5432"
