apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: default
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-service-container
          image: lucaslazaroiu/ccproject:notification-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8094
          env:
            - name: PGUSER
              value: "admin"
            - name: PGPASSWORD
              value: "admin"
            - name: PGDATABASE
              value: "movieApp"
            - name: PGHOST
              value: "postgres"
            - name: PGHOSTADDR
              value: "10.96.92.3" # PGHOSTADDR
            - name: PGPORT
              value: "5432"
            - name: TMDB_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: tmdb-config
                  key: TMDB_API_TOKEN
