apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit-deployment
  namespace: default
  labels:
    app: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8025  # Web UI
              name: web
            - containerPort: 1025  # SMTP
              name: smtp
          env:
            - name: MP_MAX_MESSAGES
              value: "500"
            - name: MP_SMTP_AUTH_ACCEPT_ANY
              value: "1"
            - name: MP_SMTP_AUTH_ALLOW_INSECURE
              value: "1"
